import type { MeetingData } from "./meeting-detector";

/**
 * Response status symbols for attendee display
 */
const RESPONSE_STATUS_SYMBOLS: Record<string, string> = {
  accepted: "\u2713",
  declined: "\u2717",
  tentative: "?",
  needsAction: "pending",
};

/**
 * NoteTemplateGenerator
 *
 * Generates structured markdown meeting notes from MeetingData.
 * Used to create pre-formatted note files for upload to Supernote Cloud.
 */
export class NoteTemplateGenerator {
  /**
   * Generate structured markdown from meeting data.
   *
   * Template includes: title, date/time, location, attendees,
   * agenda (from description), and empty sections for notes,
   * action items, and decisions.
   */
  generateMarkdown(meeting: MeetingData): string {
    const sections: string[] = [];

    // Title
    sections.push(`# ${meeting.title}`);
    sections.push("");

    // Date and time
    const { dateStr, timeStr } = this.formatDateTime(
      meeting.startTime,
      meeting.endTime,
    );
    sections.push(`**Date:** ${dateStr}`);
    sections.push(`**Time:** ${timeStr}`);

    // Location (only if present)
    if (meeting.location) {
      sections.push(`**Location:** ${meeting.location}`);
    }

    sections.push("");

    // Attendees
    sections.push("## Attendees");
    sections.push("");
    if (meeting.attendees.length === 0) {
      sections.push("No attendees listed");
    } else {
      for (const attendee of meeting.attendees) {
        const name = attendee.displayName || attendee.email;
        const symbol =
          RESPONSE_STATUS_SYMBOLS[attendee.responseStatus] ||
          attendee.responseStatus;
        sections.push(`- ${name} (${attendee.email}) - ${symbol}`);
      }
    }

    sections.push("");

    // Agenda
    sections.push("## Agenda");
    sections.push("");
    if (meeting.description) {
      let description = this.stripHtml(meeting.description);
      if (description.length > 2000) {
        description = description.substring(0, 2000) + "...";
      }
      sections.push(description);
    } else {
      sections.push("No agenda provided");
    }

    sections.push("");
    sections.push("---");
    sections.push("");

    // Notes (empty for user to fill)
    sections.push("## Notes");
    sections.push("");
    sections.push("");
    sections.push("");

    // Action Items
    sections.push("## Action Items");
    sections.push("");
    sections.push("- [ ] ");
    sections.push("- [ ] ");
    sections.push("- [ ] ");
    sections.push("");

    // Decisions
    sections.push("## Decisions");
    sections.push("");
    sections.push("");
    sections.push("");

    // Footer
    sections.push("---");
    sections.push("*Generated by Supernote Calendar Integration*");
    sections.push("");

    return sections.join("\n");
  }

  /**
   * Generate a filename for the meeting note.
   *
   * - Recurring meetings: YYYY-MM-DD [Sanitized Title].md
   * - Ad-hoc meetings: YYYY-MM-DD HH-MM [Sanitized Title].md
   *   (includes time to avoid collisions in shared Ad-Hoc folder)
   */
  generateFileName(meeting: MeetingData): string {
    const date = new Date(meeting.startTime);
    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, "0");
    const dd = String(date.getDate()).padStart(2, "0");
    const datePrefix = `${yyyy}-${mm}-${dd}`;

    const sanitizedTitle = this.sanitizeFileName(meeting.title);

    if (meeting.isRecurring) {
      return this.truncateFileName(`${datePrefix} ${sanitizedTitle}.md`, 100);
    }

    const hh = String(date.getHours()).padStart(2, "0");
    const min = String(date.getMinutes()).padStart(2, "0");
    return this.truncateFileName(
      `${datePrefix} ${hh}-${min} ${sanitizedTitle}.md`,
      100,
    );
  }

  /**
   * Format start/end times into human-readable date and time strings.
   * Uses Intl.DateTimeFormat for locale-aware formatting.
   */
  private formatDateTime(
    startTime: string,
    endTime: string,
  ): { dateStr: string; timeStr: string } {
    const start = new Date(startTime);
    const end = new Date(endTime);

    const dateFormatter = new Intl.DateTimeFormat("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const timeFormatter = new Intl.DateTimeFormat("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    });

    const dateStr = dateFormatter.format(start);
    const startTimeStr = timeFormatter.format(start);
    const endTimeStr = timeFormatter.format(end);
    const timeStr = `${startTimeStr} - ${endTimeStr}`;

    return { dateStr, timeStr };
  }

  /**
   * Strip HTML tags from text.
   * Simple regex-based approach for calendar event descriptions.
   */
  private stripHtml(html: string): string {
    return html.replace(/<[^>]*>/g, "").trim();
  }

  /**
   * Sanitize a string for use in a filename.
   * Replaces invalid filesystem characters with underscores.
   * Same approach as FolderOrganizer.sanitizeFolderName().
   */
  private sanitizeFileName(name: string): string {
    return name.replace(/[<>:"|?*\\/]/g, "_").trim();
  }

  /**
   * Truncate a filename to the specified max length,
   * preserving the file extension.
   */
  private truncateFileName(fileName: string, maxLength: number): string {
    if (fileName.length <= maxLength) {
      return fileName;
    }

    const extIndex = fileName.lastIndexOf(".");
    if (extIndex === -1) {
      return fileName.substring(0, maxLength).trim();
    }

    const ext = fileName.substring(extIndex);
    const nameWithoutExt = fileName.substring(0, extIndex);
    const maxNameLength = maxLength - ext.length;
    return nameWithoutExt.substring(0, maxNameLength).trim() + ext;
  }
}
