import { NoteTemplateGenerator } from "../src/services/note-template-generator";
import type { MeetingData } from "../src/services/meeting-detector";

describe("NoteTemplateGenerator", () => {
  let generator: NoteTemplateGenerator;

  beforeEach(() => {
    generator = new NoteTemplateGenerator();
  });

  describe("generateMarkdown", () => {
    test("should generate full markdown with all fields populated", () => {
      const meeting: MeetingData = {
        id: "event-123",
        title: "Weekly Team Standup",
        startTime: "2026-03-18T10:00:00-04:00",
        endTime: "2026-03-18T11:00:00-04:00",
        attendees: [
          {
            email: "alice@example.com",
            displayName: "Alice Smith",
            responseStatus: "accepted",
          },
          {
            email: "bob@example.com",
            displayName: "Bob Jones",
            responseStatus: "declined",
          },
          {
            email: "carol@example.com",
            displayName: "Carol Lee",
            responseStatus: "tentative",
          },
          {
            email: "dave@example.com",
            displayName: "Dave Kim",
            responseStatus: "needsAction",
          },
        ],
        description: "Discuss sprint progress and blockers.",
        location: "Conference Room B",
        isRecurring: true,
        recurringEventId: "recurring-abc",
      };

      const markdown = generator.generateMarkdown(meeting);

      expect(markdown).toContain("# Weekly Team Standup");
      expect(markdown).toContain("**Date:** Wednesday, March 18, 2026");
      expect(markdown).toContain("**Time:**");
      expect(markdown).toContain("**Location:** Conference Room B");

      // Attendees with correct symbols
      expect(markdown).toContain("- Alice Smith (alice@example.com) - \u2713");
      expect(markdown).toContain("- Bob Jones (bob@example.com) - \u2717");
      expect(markdown).toContain("- Carol Lee (carol@example.com) - ?");
      expect(markdown).toContain("- Dave Kim (dave@example.com) - pending");

      // Agenda
      expect(markdown).toContain("## Agenda");
      expect(markdown).toContain("Discuss sprint progress and blockers.");

      // Empty sections for user
      expect(markdown).toContain("## Notes");
      expect(markdown).toContain("## Action Items");
      expect(markdown).toContain("- [ ] ");
      expect(markdown).toContain("## Decisions");

      // Footer
      expect(markdown).toContain(
        "*Generated by Supernote Calendar Integration*",
      );
    });

    test("should handle minimal meeting data (no description, no attendees, no location)", () => {
      const meeting: MeetingData = {
        id: "event-456",
        title: "Quick Chat",
        startTime: "2026-03-20T14:00:00Z",
        endTime: "2026-03-20T14:30:00Z",
        attendees: [],
        isRecurring: false,
      };

      const markdown = generator.generateMarkdown(meeting);

      expect(markdown).toContain("# Quick Chat");
      expect(markdown).toContain("**Date:**");
      expect(markdown).toContain("**Time:**");
      expect(markdown).not.toContain("**Location:**");
      expect(markdown).toContain("No attendees listed");
      expect(markdown).toContain("No agenda provided");
      expect(markdown).toContain("## Notes");
      expect(markdown).toContain("## Action Items");
      expect(markdown).toContain("## Decisions");
    });

    test("should strip HTML tags from description", () => {
      const meeting: MeetingData = {
        id: "event-789",
        title: "Planning Meeting",
        startTime: "2026-03-21T09:00:00Z",
        endTime: "2026-03-21T10:00:00Z",
        attendees: [],
        description:
          "<p>Review <b>Q2 goals</b></p><ul><li>Item 1</li><li>Item 2</li></ul>",
        isRecurring: false,
      };

      const markdown = generator.generateMarkdown(meeting);

      expect(markdown).not.toContain("<p>");
      expect(markdown).not.toContain("<b>");
      expect(markdown).not.toContain("</b>");
      expect(markdown).not.toContain("<ul>");
      expect(markdown).not.toContain("<li>");
      expect(markdown).toContain("Review Q2 goals");
      expect(markdown).toContain("Item 1");
      expect(markdown).toContain("Item 2");
    });

    test("should truncate very long descriptions to 2000 chars", () => {
      const longDescription = "A".repeat(3000);
      const meeting: MeetingData = {
        id: "event-long",
        title: "Long Meeting",
        startTime: "2026-03-22T09:00:00Z",
        endTime: "2026-03-22T10:00:00Z",
        attendees: [],
        description: longDescription,
        isRecurring: false,
      };

      const markdown = generator.generateMarkdown(meeting);

      // Description should be truncated to 2000 chars + "..."
      const agendaSection = markdown.split("## Agenda")[1].split("---")[0];
      expect(agendaSection).toContain("...");
      // The truncated description should be at most 2003 chars (2000 + "...")
      const descriptionLine = agendaSection.trim();
      expect(descriptionLine.length).toBeLessThanOrEqual(2003);
    });

    test("should use email as name when displayName is missing", () => {
      const meeting: MeetingData = {
        id: "event-no-names",
        title: "Sync",
        startTime: "2026-03-23T15:00:00Z",
        endTime: "2026-03-23T15:30:00Z",
        attendees: [
          {
            email: "unknown@example.com",
            responseStatus: "accepted",
          },
        ],
        isRecurring: false,
      };

      const markdown = generator.generateMarkdown(meeting);

      expect(markdown).toContain(
        "- unknown@example.com (unknown@example.com) - \u2713",
      );
    });

    test("should pass through unknown response statuses as-is", () => {
      const meeting: MeetingData = {
        id: "event-unknown-status",
        title: "Mystery Meeting",
        startTime: "2026-03-24T10:00:00Z",
        endTime: "2026-03-24T11:00:00Z",
        attendees: [
          {
            email: "guest@example.com",
            displayName: "Guest",
            responseStatus: "unknownStatus",
          },
        ],
        isRecurring: false,
      };

      const markdown = generator.generateMarkdown(meeting);

      expect(markdown).toContain("- Guest (guest@example.com) - unknownStatus");
    });
  });

  describe("generateFileName", () => {
    test("should generate date-only filename for recurring meetings", () => {
      const meeting: MeetingData = {
        id: "event-rec-1",
        title: "Daily Standup",
        startTime: "2026-03-18T10:00:00Z",
        endTime: "2026-03-18T10:15:00Z",
        attendees: [],
        isRecurring: true,
        recurringEventId: "recurring-daily",
      };

      const fileName = generator.generateFileName(meeting);

      expect(fileName).toBe("2026-03-18 Daily Standup.md");
    });

    test("should generate date+time filename for ad-hoc meetings", () => {
      const meeting: MeetingData = {
        id: "event-adhoc-1",
        title: "Project Review",
        startTime: "2026-03-20T14:30:00Z",
        endTime: "2026-03-20T15:30:00Z",
        attendees: [],
        isRecurring: false,
      };

      const fileName = generator.generateFileName(meeting);

      expect(fileName).toBe("2026-03-20 14-30 Project Review.md");
    });

    test("should sanitize special characters in title", () => {
      const meeting: MeetingData = {
        id: "event-special",
        title: 'Review: "Q2 Goals" | Sprint <5> Plan',
        startTime: "2026-03-21T09:00:00Z",
        endTime: "2026-03-21T10:00:00Z",
        attendees: [],
        isRecurring: false,
      };

      const fileName = generator.generateFileName(meeting);

      expect(fileName).not.toContain(":");
      expect(fileName).not.toContain('"');
      expect(fileName).not.toContain("|");
      expect(fileName).not.toContain("<");
      expect(fileName).not.toContain(">");
      expect(fileName).toContain("Review_ _Q2 Goals_ _ Sprint _5_ Plan");
      expect(fileName.endsWith(".md")).toBe(true);
    });

    test("should truncate filename to 100 chars", () => {
      const longTitle = "A".repeat(120);
      const meeting: MeetingData = {
        id: "event-long-title",
        title: longTitle,
        startTime: "2026-03-22T09:00:00Z",
        endTime: "2026-03-22T10:00:00Z",
        attendees: [],
        isRecurring: true,
      };

      const fileName = generator.generateFileName(meeting);

      expect(fileName.length).toBeLessThanOrEqual(100);
      expect(fileName.endsWith(".md")).toBe(true);
    });

    test("should truncate ad-hoc filename to 100 chars", () => {
      const longTitle = "B".repeat(120);
      const meeting: MeetingData = {
        id: "event-long-adhoc",
        title: longTitle,
        startTime: "2026-03-22T15:45:00Z",
        endTime: "2026-03-22T16:45:00Z",
        attendees: [],
        isRecurring: false,
      };

      const fileName = generator.generateFileName(meeting);

      expect(fileName.length).toBeLessThanOrEqual(100);
      expect(fileName.endsWith(".md")).toBe(true);
    });

    test("should zero-pad month, day, hours, minutes", () => {
      const meeting: MeetingData = {
        id: "event-pad",
        title: "Morning Sync",
        startTime: "2026-01-05T08:05:00Z",
        endTime: "2026-01-05T08:30:00Z",
        attendees: [],
        isRecurring: false,
      };

      const fileName = generator.generateFileName(meeting);

      expect(fileName).toBe("2026-01-05 08-05 Morning Sync.md");
    });
  });
});
